$( document ).ready(function() {
var TABLEPRICE="<div class='container'><h2 class='tp ts4 racing mb-5'>HARGA TEMPLATE TOKO ONLINE BLOGSPOT</h2><div class='row'><div class='col-sm-12 col-md-4 t-price text-center'>";

TABLEPRICE+="<h3 class='racing tp ts3'>LAPAKIMPLE</h3><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fb'/><i class='fas fa-star fb'/><div class='old-price'>Rp 250.000</div><div class='cur-price ts3' data-price='150000'>Rp 150.000</div><ul class='t-desc'><li>1 Lisensi</li><li>Dapat 1 Template</li><li>Gratis Update Ongkir</li><li>Gratis Update Template</li><li>Dukungan SSL</li><li>Unlimited Produk</li><li>Tidak Dapat Domain Gratis</li><li>Dukungan Penuh </li></ul>  <button class='btn btn-pink mb-3' type='button'><a class='link-ww' href='www.lapakhijab.online' target='_blank'>Coba Dulu</a></button></div><div class='col-sm-12 col-md-4 t-price-best text-center'><h3 class='racing tp ts3'>PRO</h3><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><div class='old-price'>Rp 749.000</div><div class='cur-price ts3' data-price='150000'>Rp 299.000</div><ul class='t-desc'><li>4 Lisensi</li><li>Gratis 1 Lisensi Lagi</li><li>Dapat 3 Template</li><li>Gratis Domain web.id</li><li>Gratis Update Ongkir</li><li>Gratis Update Template</li><li>Dukungan SSL</li><li>Unlimited Produk</li><li>Dukungan Penuh</li></ul>  <button class='btn btn-purple mb-3' type='button'><a class='link-ww' href='www.lapakhijab.online' target='_blank'>Serius Buat Toko</a></button></div>";

TABLEPRICE+="<h3 class='racing tp ts3'>LAPAKINLINE</h3><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fb'/><i class='fas fa-star fb'/><div class='old-price'>Rp 250.000</div><div class='cur-price ts3' data-price='150000'>Rp 150.000</div><ul class='t-desc'><li>1 Lisensi</li><li>Dapat 1 Template</li><li>Gratis Update Ongkir</li><li>Gratis Update Template</li><li>Dukungan SSL</li><li>Unlimited Produk</li><li>Tidak Dapat Domain Gratis</li><li>Dukungan Penuh </li></ul>  <button class='btn btn-pink mb-3' type='button'><a class='link-ww' href='www.lapakhijab.online' target='_blank'>Coba Dulu</a></button></div><div class='col-sm-12 col-md-4 t-price-best text-center'><h3 class='racing tp ts3'>PRO</h3><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><div class='old-price'>Rp 749.000</div><div class='cur-price ts3' data-price='150000'>Rp 299.000</div><ul class='t-desc'><li>4 Lisensi</li><li>Gratis 1 Lisensi Lagi</li><li>Dapat 3 Template</li><li>Gratis Domain web.id</li><li>Gratis Update Ongkir</li><li>Gratis Update Template</li><li>Dukungan SSL</li><li>Unlimited Produk</li><li>Dukungan Penuh</li></ul>  <button class='btn btn-purple mb-3' type='button'><a class='link-ww' href='www.lapakhijab.online' target='_blank'>Serius Buat Toko</a></button></div>";

TABLEPRICE+="<h3 class='racing tp ts3'>LAPAKHIJAB</h3><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fb'/><i class='fas fa-star fb'/><div class='old-price'>Rp 250.000</div><div class='cur-price ts3' data-price='150000'>Rp 150.000</div><ul class='t-desc'><li>1 Lisensi</li><li>Dapat 1 Template</li><li>Gratis Update Ongkir</li><li>Gratis Update Template</li><li>Dukungan SSL</li><li>Unlimited Produk</li><li>Tidak Dapat Domain Gratis</li><li>Dukungan Penuh </li></ul>  <button class='btn btn-pink mb-3' type='button'><a class='link-ww' href='www.lapakhijab.online' target='_blank'>Coba Dulu</a></button></div><div class='col-sm-12 col-md-4 t-price-best text-center'><h3 class='racing tp ts3'>PRO</h3><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><i class='fas fa-star fs'/><div class='old-price'>Rp 749.000</div><div class='cur-price ts3' data-price='150000'>Rp 299.000</div><ul class='t-desc'><li>4 Lisensi</li><li>Gratis 1 Lisensi Lagi</li><li>Dapat 3 Template</li><li>Gratis Domain web.id</li><li>Gratis Update Ongkir</li><li>Gratis Update Template</li><li>Dukungan SSL</li><li>Unlimited Produk</li><li>Dukungan Penuh</li></ul>  <button class='btn btn-purple mb-3' type='button'><a class='link-ww' href='www.lapakhijab.online' target='_blank'>Serius Buat Toko</a></button></div></div></div>";

$('.regular').html(TABLEPRICE);
});
